plugins { id 'com.android.application' }

android {
    namespace 'com.aadityasamriya.needle2'
    compileSdk 35
    defaultConfig {
        applicationId 'com.aadityasamriya.needle2'
        minSdk 28
        targetSdk 35
        versionCode 4
        versionName '2.0.0'
    }
    buildTypes {
        release { minifyEnabled false; signingConfig signingConfigs.debug }
        debug { minifyEnabled false }
    }
}
